### ISSUE TITLE
Create app icon

### ISSUE THREAD

**Issue by justinalexandershaw** [PrepTimer/PrepTime#16]
Create the app icon from this image.
![PrepTimerLogo](https://user-images.githubusercontent.com/46334750/101449879-6eef3e00-38de-11eb-97f8-c2c74068988a.png)

**Comment by sorenrood** [comment]
Okay Justin I see you. :eyes:

**Comment by justinalexandershaw** [comment]
I'm gonna leave this here for reference: https://pub.dev/packages/flutter_launcher_icons

**Comment by justinalexandershaw** [comment]
![PrepTimerLogo](https://user-images.githubusercontent.com/46334750/102051483-7a88ac00-3d99-11eb-8909-8d95ce5ea2f1.png)
 Leaving this here to remove it from my desktop
