### ISSUE TITLE
Test Provider Models

### ISSUE THREAD

**Issue by justinalexandershaw** [PrepTimer/PrepTime#2]
We need to set up some test files to cover the provider models. Then, we can set up some tests when we merge branches.

- [x] CountDownTimer
- [x] DebateEvent
- [x] EventController
- [x] Event
- [x] PrepTimeMixin
- [x] SpeechEvent
- [x] SpeechStatus
- [x] Speech
- [x] Team
- [x] Timeable

**Comment by justinalexandershaw** [comment]
Finished 11 tests for countdowntimer

**Comment by justinalexandershaw** [comment]
finished 7 tests for debateEvent

**Comment by justinalexandershaw** [comment]
finished 9 tests for eventController

**Comment by justinalexandershaw** [comment]
finished 6 tests for Event

**Comment by justinalexandershaw** [comment]
finished prepTimeMixin

**Comment by justinalexandershaw** [comment]
finished 6 tests for speechEvent

**Comment by justinalexandershaw** [comment]
Alright so here's the deal; I don't really know how to test enums and I honestly don't think I should. So I am gonna go ahead and mark off the `SpeechStatus` and `Team` enums.

**Comment by justinalexandershaw** [comment]
Not gonna do `Timeable` either

**Comment by justinalexandershaw** [comment]
I'm about half-done with the MockSpeech class and I'm having trouble with the ticker.

**Comment by justinalexandershaw** [comment]
Ugh, this is giving me PTSD from when I was waist-deep in Mockito and FlutterTesting this summer @sorenrood :)

**Comment by sorenrood** [comment]
Lol. I don't know flutter, but I may be able to help with tests...? I'm also familiar with enum testing...? Talk soon!

**Comment by sorenrood** [comment]
Maybe... Or not... Not sure... 👾

**Comment by justinalexandershaw** [comment]
![LGTM](https://camo.githubusercontent.com/b8663222673094c7b438569f780df8c3608b93019515d157e7fc04f11774fd0a/68747470733a2f2f692e696d6775722e636f6d2f4a674e52616c492e706e67)
