### ISSUE TITLE
Implement time signals and auto-move speeches.

### ISSUE THREAD

**Issue by justinalexandershaw** [PrepTimer/PrepTime#6]
We still need to implement time signals and auto-advance the speeches when the timer finishes. That means:
- [x] Add time signal assets
- [x] Add a time signal handler in the UI code for a speech
- [x] Change speech API to trigger a time signal

https://github.com/PrepTimer/PrepTime/blob/21dc144114d0bf7bbdcb24ec202d302e281e08e5/lib/provider/models/speech.dart#L136-L163

**Comment by justinalexandershaw** [comment]
gonna work on this tomorrow @sorenrood

**Comment by sorenrood** [comment]
Yay I got the notification. :)
